# Numpy

In [1]:
import numpy as np

`Basic`

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
# all data type must be same 
a = np.array([1,2,3,"4"])

print(a)

['1' '2' '3' '4']


In [6]:
 l = [[1,2,3],[4,5,6],[7,8,9]]
 l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [16]:
np.random.randint(1,10,size=[3,3])

array([[1, 4, 7],
       [5, 7, 8],
       [8, 5, 2]], dtype=int32)

`Array Methods`

In [ ]:


arr = np.random.randint(1,10,size=[3,3])
arr

array([[8, 1, 5],
       [4, 8, 4],
       [9, 9, 3]], dtype=int32)

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [22]:
arr.dtype

dtype('int32')

`Array Methods`

In [23]:
arr

array([[8, 1, 5],
       [4, 8, 4],
       [9, 9, 3]], dtype=int32)

In [24]:
arr.min()

np.int32(1)

In [25]:
arr.max()

np.int32(9)

In [26]:
arr.sum()

np.int64(51)

In [ ]:
np.sum(arr,axis=1)
# 1 - row wise ,  0 - col wise 

array([14, 16, 21])

In [28]:
arr.mean()

np.float64(5.666666666666667)

In [29]:
arr.std()

np.float64(2.748737083745107)

In [30]:
arr.argmax()

np.int64(6)

`Reshape`

In [31]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

`Array Indexing`

In [34]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
arr[6]

np.int64(17)

In [36]:
arr[1:5]

array([12, 13, 14, 15])

In [37]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [38]:
arr[3::3]

array([14, 17, 20])

In [39]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])